Lab refresh - 4000
oracle-livelabs/developer pull request #238
Opened 2023-10-03 15:34 UTC by aberinnj

# Add here your WMS ID
4000

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [X] All filenames are lower case (including folders, images, files, etc.)
- [X] Filenames are descriptive
- [X] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [X] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [X] Image references in markdown contain an alternate text

2023-10-03 16:13 UTC, denisemyrick requested changes

2023-10-03 16:13 UTC, denisemyrick commented on mytodoreact/frontend/frontend.md
Please ensure this isn't jumping from task 2 to task 4.

2023-10-03 16:13 UTC, denisemyrick commented on mytodoreact/teardown/teardown.md
looks like you have two task 4s

2023-10-04 04:17 UTC, aberinnj commented
@denisemyrick Thank you for reviewing so far, please give it another look!

2023-10-04 13:37 UTC, denisemyrick submitted a review, later dismissed

2023-10-04 13:37 UTC, denisemyrick commented on mytodoreact/intro/images/Application.png
You still need to rename Application.png to application.png

2023-10-05 17:22 UTC, ramumg approved these changes

2023-10-05 17:22 UTC, merged