init for  "Develop with Oracle AI and Database Services: Healthcare (Open Source Version)" workshop WMSID 11485
oracle-livelabs/developer pull request #250
Opened 2023-12-30 20:43 UTC by paulparkinson

# 11485

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [x ] All filenames are lower case (including folders, images, files, etc.)
- [ x] Filenames are descriptive
- [ x] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ x] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ x] Image references in markdown contain an alternate text

2024-01-02 15:00 UTC, denisemyrick requested changes
HI Paul, please update the branch to merge with master. Also I noted OracleHealthAI-FlutterSpringBootStack.png and OracleHealthAI-MERNStack.png need to be updated to be lower case. I'll complete the review once the branch is updated. 

Thanks

2024-01-02 15:16 UTC, paulparkinson commented
Thanks @denisemyrick !  Sorry I'm confused as I think it is merging to main (which is master) currently?  I made the modes to lower case OracleHealthAI-FlutterSpringBootStack.png and OracleHealthAI-MERNStack.png

2024-01-02 19:53 UTC, ramumg reviewed
Please make sure you follow the QA

2024-01-02 19:53 UTC, ramumg commented on oracle-health-ai-open-source/ai-document-flutter-ui/ai-document-flutter-ui.md
Please make sure to check the spelling. According is spelled out wrong.

2024-01-02 20:47 UTC, paulparkinson commented on oracle-health-ai-open-source/ai-document-flutter-ui/ai-document-flutter-ui.md
thanks @ramumg fixed that a few others in the push I just made.

2024-01-03 14:56 UTC, denisemyrick requested changes

2024-01-03 14:56 UTC, denisemyrick commented on oracle-health-ai-open-source/ai-vision-setup/ai-vision-setup.md
task 7 skips step 5

2024-01-03 15:47 UTC, paulparkinson commented on oracle-health-ai-open-source/ai-vision-setup/ai-vision-setup.md
@denisemyrick got it :) thanks.

2024-01-03 18:29 UTC, rahul-tasker approved these changes

2024-01-03 19:53 UTC, denisemyrick approved these changes

2024-01-03 19:53 UTC, merged